version: '3.3'

services:
    redis:
      image: 'redis:latest'
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
       - redis-data:/data

volumes:
  redis-data:
