version: '3.3'

services:
    redis:
      image: 'redis:latest'
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      networks:
      - database
      volumes:
       - redis-data:/data

    api:
     build:
       context: .
       dockerfile: Dockerfile
     networks:
       - database
     ports:
       - "8080:8080"

volumes:
  redis-data:

networks:
  database:
